# Generated by Django 3.2 on 2023-03-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230219_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title_image',
            field=models.BooleanField(default=True),
        ),
    ]
