# Generated by Django 3.2 on 2023-04-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20230421_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbucketproducts',
            name='bucket_products',
        ),
        migrations.RemoveField(
            model_name='userbucketproducts',
            name='quantity',
        ),
        migrations.AddField(
            model_name='userbucketproducts',
            name='user_bucket',
            field=models.JSONField(null=True),
        ),
    ]
