# Generated by Django 3.2 on 2023-05-01 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0017_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(null=True, verbose_name='Products in order'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('ONLINE_PAYMENT', 'Online payment'), ('PAYMENT_BY_CARD', 'Payment by card upon receipt'), ('PAYMENT_IN_CASH', 'Cash payment'), ('CASH_ON_DELIVERY', 'Cash on delivery')], default='ONLINE_PAYMENT', max_length=50),
        ),
    ]
