# Generated by Django 3.2 on 2023-04-28 14:03

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(default=products.models.Order.products_ordered, verbose_name='Products in order'),
        ),
    ]
