# Generated by Django 3.2 on 2023-04-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.JSONField(null=True, verbose_name='Products in order'),
        ),
    ]
