# Generated by Django 3.2 on 2023-07-28 12:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_shopaddress_shopcontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcontacts',
            name='email_2',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shopcontacts',
            name='email_3',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shopcontacts',
            name='email_4',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shopcontacts',
            name='phone_number_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UA', unique=True),
        ),
        migrations.AddField(
            model_name='shopcontacts',
            name='phone_number_3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UA', unique=True),
        ),
        migrations.AddField(
            model_name='shopcontacts',
            name='phone_number_4',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UA', unique=True),
        ),
        migrations.AddField(
            model_name='shopcontacts',
            name='service',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
